string = "   i aM currEntly woRking on pytHon prograMming!!     "
print(string)
print(string.upper())
print(string.lower())
print(string.title())
print(string.strip())
print(string.lstrip())
print(string.rstrip())
print(string.find("on"))
print(string.replace("o", "h"))
print("pro" in string)
print("am" in string)
